### ISSUE TITLE
Arch Linux上でインストールができない

### ISSUE THREAD

**Issue by tkna91** [team-apm/apm#1430]
## バグの説明

インストールができない

## 再現手順

動作を再現する手順:

1. 'おすすめインストール' の 'インストール' をクリック
2. 端末上にエラーが出力される
3. インストール先に指定したディレクトリは空のままになっている

ログ

```bash
[a@gb1 aviutl]$ aviutl-package-manager
15:45:57.103 › {
  node: '18.15.0',
  v8: '11.4.183.23-electron.0',
  uv: '1.44.2',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.19.1',
  modules: '116',
  nghttp2: '1.55.1',
  napi: '8',
  llhttp: '6.0.10',
  uvwasi: '0.0.15',
  acorn: '8.8.2',
  simdutf: '3.1.0',
  undici: '5.20.0',
  openssl: '1.1.1',
  cldr: '43.1',
  icu: '73.2',
  tz: '2023c',
  unicode: '15.0',
  electron: '25.6.0',
  chrome: '114.0.5735.134'
}
[392410:0907/154557.164468:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[392410:0907/154557.164530:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
15:45:57.995 › No updates are found
[392443:0907/154602.383966:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[392443:0907/154603.665921:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
15:46:03.817 › Error: spawn ENOTDIR
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.run (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/lifecycle.js:74:26)
    at main (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/main.js:55:15)
    at extractFull (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/commands.js:27:10)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:36:21
    at Generator.next (<anonymous>)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1
    at new Promise (<anonymous>)
    at folderName (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1)
    at t.default (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:20:39)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:474:32
    at Generator.next (<anonymous>)
    at s (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/common.ts:97:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
15:46:03.974 › Error: spawn ENOTDIR
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.run (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/lifecycle.js:74:26)
    at main (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/main.js:55:15)
    at extractFull (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/commands.js:27:10)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:36:21
    at Generator.next (<anonymous>)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1
    at new Promise (<anonymous>)
    at folderName (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1)
    at t.default (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:20:39)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:474:32
    at Generator.next (<anonymous>)
    at s (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/common.ts:97:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
15:46:03.990 › Error: spawn ENOTDIR
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.run (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/lifecycle.js:74:26)
    at main (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/main.js:55:15)
    at extractFull (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/commands.js:27:10)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:36:21
    at Generator.next (<anonymous>)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1
    at new Promise (<anonymous>)
    at folderName (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1)
    at t.default (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:20:39)
    at Object.core (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/package.ts:765:22)
    at Generator.next (<anonymous>)
    at core (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:560:16)
    at new Promise (<anonymous>)
    at s (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:560:16)
    at getUnzippedPath (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/package.ts:763:41)
    at Object.core (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/package.ts:781:32)
    at Generator.next (<anonymous>)
    at s (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:560:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
15:46:03.996 › Error: spawn ENOTDIR
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.run (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/lifecycle.js:74:26)
    at main (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/main.js:55:15)
    at extractFull (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/node_modules/node-7z/src/commands.js:27:10)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:36:21
    at Generator.next (<anonymous>)
    at /opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1
    at new Promise (<anonymous>)
    at folderName (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/shortcut.ts:45:1)
    at t.default (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/lib/unzip.ts:20:39)
    at Object.core (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/package.ts:765:22)
    at Generator.next (<anonymous>)
    at core (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:560:16)
    at new Promise (<anonymous>)
    at s (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:560:16)
    at getUnzippedPath (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/package.ts:763:41)
    at Object.core (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/package.ts:781:32)
    at Generator.next (<anonymous>)
    at s (/opt/aviutl-package-manager/aviutl-package-manager.asar/.webpack/renderer/main_window/webpack:/apm/src/renderer/main/core.ts:560:16)
[392443:0907/154607.027874:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[a@gb1 aviutl]$ pwd
/home/a/ext/app/aviutl
[a@gb1 aviutl]$ ls -Fla
合計 0
drwxr-xr-x 1 a a   0  9月  7 14:05 ./
drwxr-xr-x 1 a a 100  9月  7 14:05 ../
[a@gb1 aviutl]$
```

## 期待していた動作

インストール先にインストール対象がインストールされる

## スクリーンショット

https://github.com/team-apm/apm/assets/102382754/93c1b504-f787-4e02-9d87-3c94650450e8

## デスクトップ（以下の情報を入力してください）:

- OS: Arch Linux x86_64
- Kernel: 6.4.12-arch1-1
- WM: sway
- インストール用パッケージ: https://aur.archlinux.org/cgit/aur.git/tree/?h=aviutl-package-manager-bin

**Comment by mitosagi** [comment]
I think the distribution of non-debugged Linux versions of apm should be stopped as it causes confusion.

I am not familiar with it, but is it possible to make apm work with wine?

**Comment by tkna91** [comment]
@mitosagi I have not done it yet, but it seems possible to use AviUtl with Wine in this way.
https://deep.tacoskingdom.com/blog/137

**Comment by hal-shu-sato** [comment]
長らく放置してしまい申し訳ありません。改めて調べたところ、この件は #2180 の `7za EACCES` とは**別の原因**でした。

## 原因

ログのエラーは `spawn ENOTDIR` で、これは「実行ファイルのパスの途中がディレクトリでない」ときに出ます。パスに注目すると:

```
/opt/aviutl-package-manager/aviutl-package-manager.asar/...
```

**asar のファイル名が `app.asar` ではありません。** apm は 7za のパスを解決するとき

```ts
pathTo7zip.replace('app.asar', 'app.asar.unpacked')
```

というリテラル置換をしています。`aviutl-package-manager.asar` にはこの文字列が含まれないため置換が発火せず、7za のパスが asar の**内側**を指したまま spawn され、`ENOTDIR` になります。

## これは公式ビルドではありません

`/opt/<名前>/<名前>.asar` というレイアウトは electron-forge の deb / rpm が作るものではなく(forge は `resources/app.asar` に置きます)、AUR 等で再パッケージされたものだと思われます。そのため apm の公式インストーラでは再現しないはずです。

## 対応の選択肢

1. **再パッケージ側で直す** — asar 名を変えない、あるいは 7za を asar の外へ確実に展開する
2. **apm 側を堅牢化する** — 置換を asar 名に依存しない形(`/\.asar([\\/])/` → `.asar.unpacked$1`)にする。ただしこれは「再パッケージ側が実際に unpack している」ことが前提で、unpack されていなければこの変更でも直りません

また 2023 年の報告のため、apm 側も当時から大きく変わっています(直近の v3.13.0 では 7za まわりの修正も入りました)。

## お願い

現在も再現するかどうか、もし可能であれば **公式のビルド**(GitHub Releases の deb / rpm / zip)でも試していただけると切り分けができます。公式ビルドで再現しないようであれば、上記 1 の線が濃厚ということになります。

---

調査と文面の作成に [Claude Code](https://claude.com/claude-code) を使用しています。
