### ISSUE TITLE
The app shows error upon startup on Linux Mint 21.3

### ISSUE THREAD

**Issue by EggToaster** [team-apm/apm#1883]
## Describe the bug
When I launch APM on Linux Mint 21.3(Ubuntu 22 based), I get the error.
Screenshot is attached.
The system is almost fully up to date. I cannot upgrade to Linux Mint 22 as Ubuntu 24 has a lot of missing packages.

## To Reproduce

Only step is to launch the app. I still can say that I installed app through Debian package(deb).

## Expected behavior
I don't know, launch the app without error?

## Screenshots
![image](https://github.com/user-attachments/assets/79ad8a00-c549-4266-a021-c7a78774b5e4)

## Desktop (please complete the following information):

- OS: Linux Mint 21.3 Virginia
- Version: 3.8.0 with Debian package

## Additional context
Full error log:
`[2024-10-18 13:57:00.942] [debug] {
  node: '18.17.1',
  acorn: '8.8.2',
  ada: '2.5.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '118',
  napi: '9',
  nghttp2: '1.52.0',
  openssl: '1.1.1',
  simdutf: '3.2.12',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.18',
  v8: '11.8.172.18-electron.0',
  zlib: '1.2.13.1-motley',
  electron: '27.3.2',
  chrome: '118.0.5993.159'
}
[2024-10-18 13:57:17.670] [error] Unhandled TypeError: a.setTitleBarOverlay is not a function
    at NativeTheme.<anonymous> (/usr/lib/apm/resources/app.asar/.webpack/main/index.js:8:254891)
    at NativeTheme.emit (node:events:514:28)
[2024-10-18 13:57:19.503] [error] Unhandled TypeError: a.setTitleBarOverlay is not a function
    at NativeTheme.<anonymous> (/usr/lib/apm/resources/app.asar/.webpack/main/index.js:8:254891)
    at NativeTheme.emit (node:events:514:28)
[2024-10-18 13:57:19.823] [error] Unhandled Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:110219)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)`
Note: I can get it to work on Wine, so this should not be on highest priority.

**Comment by hal-shu-sato** [comment]
Sorry for the long delay on this one.

We have just released **v3.14.0**, which includes a fix for a startup crash: when the update check or the nicommons request failed, the error was not handled and the app terminated. If the error you saw was related to network access at startup, that may well be it.

Could you check whether the problem still happens on **v3.14.0 or later**?

If it does, we would need a bit more than the screenshot to narrow it down:

- The **error text** itself (copy-paste rather than an image, if possible)
- The output of launching apm from a terminal — that usually shows Electron and GTK errors that never reach the dialog
- The contents of `~/.config/AviUtl Package Manager/logs/main.log` around the time of the error

One thing worth noting: apm is developed and tested primarily on Windows, and the Linux builds get much less real-world coverage. Distribution-specific issues (missing GTK/portal components on Ubuntu 22 based systems, for example) are plausible here, so terminal output is especially valuable.

---

Investigation and drafting done with [Claude Code](https://claude.com/claude-code).
